name: monthly_focus

description: "매월 4가지 목표를 설정하고 체크하는 습관 형성 앱"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 기본 아이콘 패키지
  cupertino_icons: ^1.0.2

  # 상태 관리
  provider: ^6.1.1

  # 로컬 데이터 저장
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # 날짜/시간 처리
  intl: ^0.19.0

  # 푸시 알림
  flutter_local_notifications: ^16.3.0

  # SNS 공유 (App Store 심사 문제로 제거)
  # share_plus: ^11.0.0

  # 이미지 저장
  path_provider: ^2.1.1
  screenshot: ^2.1.0

  # 앱 설정 (App Store 심사 문제로 package_info_plus 제거)
  # package_info_plus: ^8.3.0
  flutter_native_timezone: ^2.0.0

  # UI 컴포넌트
  flutter_slidable: ^3.0.1
  table_calendar: ^3.0.9
  flutter_emoji: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Monthly Focus_1.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/Monthly Focus_1.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
  - assets/icons/ 
